### ISSUE TITLE
Wee Bit Gay

### ISSUE THREAD

**Issue by LieutenantGhost** [JTGhawk137/Genetic-Algorithm-Test#2]
Your program here seems a _little_ too **homo** for my tastes. It seems to me that it is only prolonging your **crippling** depression, and wasting time. Try suicide maybe, then give me **creator-authority** over this project. Disrupt the sustainability horizontally. **Yolo**.

**Comment by LieutenantGhost** [comment]
Remember, just a _little_ homo.

**Comment by JTGhawk137** [comment]
Too real
